### ISSUE TITLE
can't upload a CAR with the client library

### ISSUE THREAD

**Issue by mikeal** [web3-storage/w3up-client#34]
I've setup the `w3up` cli and i can upload regular files with that client successfully.

However, when I try to write CAR using w3up-client

```js
  const client = createClient({
    serviceDID: 'did:key:z6MkrZ1r5XBFZjBU34qyD8fueMbMRkKw17BZaq2ivKFjnz2z',
    serviceURL: 'https://8609r1772a.execute-api.us-east-1.amazonaws.com',
    accessDID: 'did:key:z6MkkHafoFWxxWVNpNXocFdU6PL2RVLyTEgS1qTnD3bRP7V9',
    accessURL: 'https://access-api.web3.storage',
    settings: new Map(),
  })

  const msg = await client.upload(cardata /* Buffer */)
```

I get:

```
Error: {
  "name": "HandlerExecutionError",
  "cause": {
    "name": "TypeError",
    "stack": "TypeError: Cannot read properties of null (reading 'error')\n    at null.<anonymous> (/src/ingestion/ucanto/store/provider.js:65:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at null.invoke3 (/node_modules/@ucanto/server/src/server.js:129:14)\n    at null.execute2 (/node_modules/@ucanto/server/src/server.js:90:18)\n    at null.handle (/node_modules/@ucanto/server/src/server.js:71:18)\n    at null.ucanHandler (/src/ingestion/ingestion.js:79:29)\n    at Runtime.handler (/node_modules/src/awslambda.ts:332:1)",
    "message": "Cannot read properties of null (reading 'error')"
  },
  "error": true,
  "stack": "HandlerExecutionError: service handler {can: \"store/add\"} error: Cannot read properties of null (reading 'error')\n    at null.invoke3 (/node_modules/@ucanto/server/src/server.js:131:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at null.execute2 (/node_modules/@ucanto/server/src/server.js:90:18)\n    at null.handle (/node_modules/@ucanto/server/src/server.js:71:18)\n    at null.ucanHandler (/src/ingestion/ingestion.js:79:29)\n    at Runtime.handler (/node_modules/src/awslambda.ts:332:1)",
  "message": "service handler {can: \"store/add\"} error: Cannot read properties of null (reading 'error')",
  "capability": {
    "can": "store/add",
    "with": "did:key:z6MktqNReihk3TAHePrTo9xsYu6ciAMuvkN46XciWuBrTFab"
  }
}
    at Client.upload (file:///Users/mikealrogers/Library/Mobile%20Documents/com~apple~CloudDocs/code/web-delta/node_modules/@web3-storage/w3up-client/src/index.js:403:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async publish (file:///Users/mikealrogers/Library/Mobile%20Documents/com~apple~CloudDocs/code/web-delta/bin.js:69:15)
    at async Object.delta [as handler] (file:///Users/mikealrogers/Library/Mobile%20Documents/com~apple~CloudDocs/code/web-delta/bin.js:93:5)
bin.js delta <origin-file> <updated-file>
```

**Comment by vantreeseba** [comment]
This is probably due to the client not having an account or etc setup.

You can get the POJO that you would turn into a map to pass into the settings using the export-settings option in the CLI for now.

This interface will be changing a bit soon when access api stuff is more tightly integrated and with #32

**Comment by ice-breaker-tg** [comment]
This is probably due to the client not having an account or etc setup.

You can get the POJO that you would turn into a map to pass into the settings using the export-settings option in the CLI for now.

This interface will be changing a bit soon when access api stuff is more tightly integrated and with https://github.com/web3-storage/w3up-client/issues/32

**Comment by mikeal** [comment]
cool, when we change stuff to the new access api let's get a more informative error in when the settings are wrong :)

i'll work on a fix on my end pulling in the proper settings.

**Comment by alanshaw** [comment]
When v4 is released you'll need to be calling https://github.com/web3-storage/w3up-client#capabilitystoreadd

We also have a test to ensure you cannot upload without first creating a space (with a nice error message): https://github.com/web3-storage/w3up-client/blob/7bd91d59da2b961a4227d9c062e74169e645a0bc/test/client.test.js#L85-L91
